In [3]:
import numpy as np

In [5]:
arr=[1,2,3,4]
my_arr=np.array(arr)

In [7]:
print(my_arr)

[1 2 3 4]


In [8]:
type(my_arr)

numpy.ndarray

In [9]:
a1=[1,2,3,4]
a2=[3,4,5,6]
a3=[7,8,9,10]

In [10]:
new_Array=np.array((a1,a2,a3))

In [11]:
new_Array

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [13]:
new_Array.shape

(3, 4)

In [19]:
new_Array[1:,:2]

array([[3, 4],
       [7, 8]])

In [23]:
new_Array[:,2:]

array([[ 3,  4],
       [ 5,  6],
       [ 9, 10]])

In [27]:
val=3
new_Array[new_Array<6]

array([1, 2, 3, 4, 3, 4, 5])

In [30]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])